name: pokedex
description: "Pokedex App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  retrofit: ^4.7.2
  dio: ^5.9.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  go_router: ^16.2.1
  cached_network_image: ^3.4.1
  flutter_svg: ^2.2.1
  json_annotation: ^4.9.0
  dartz: ^0.10.1
  get_it: ^8.2.0
  awesome_dio_interceptor: ^1.3.0
  fade_shimmer: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  retrofit_generator: ^10.0.5
  json_serializable: ^6.11.1
  build_runner: ^2.7.0
  flutter_gen_runner: ^5.11.0

flutter_gen:
  output: lib/resources
  line_length: 80

  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
